from PicoAutonomousRobotics import KitronikPicoRobotBuggy
from time import sleep

robot = KitronikPicoRobotBuggy()
robot.motorOn("l", "f", 50)
robot.motorOn("r", "f", 50)
sleep(0.5)
robot.motorOn("l", "r", 50)
robot.motorOn("r", "r", 50)
sleep(0.5)
robot.motorOff("l")
robot.motorOff("r")

robot.goToPosition(0, 0)
robot.goToPosition(1, 0)
robot.goToPosition(2, 0)
robot.goToPosition(3, 0)
sleep(0.5)
robot.goToPosition(0, 90)
robot.goToPosition(1, 90)
robot.goToPosition(2, 90)
robot.goToPosition(3, 90)
sleep(0.5)
robot.goToPosition(0, 180)
robot.goToPosition(1, 180)
robot.goToPosition(2, 180)
robot.goToPosition(3, 180)

print(robot.getDistance())
sleep(0.5)
print(robot.getDistance())

print(robot.isLFSensorLight("l"))
print(robot.isLFSensorLight("c"))
print(robot.isLFSensorLight("r"))
sleep(0.5)
print(robot.isLFSensorLight("l"))
print(robot.isLFSensorLight("c"))
print(robot.isLFSensorLight("r"))

robot.beepHorn()
sleep(0.5)
robot.beepHorn()

robot.setLED(0, robot.RED)
robot.setLED(1, robot.RED)
robot.setLED(2, robot.RED)
robot.setLED(3, robot.RED)
robot.show()
sleep(0.5)
robot.setLED(0, robot.WHITE)
robot.setLED(1, robot.WHITE)
robot.setLED(2, robot.WHITE)
robot.setLED(3, robot.WHITE)
robot.show()
